# Generated by Django 4.1.5 on 2023-05-06 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fish_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caughtfishinfo",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caught_fish_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
