# Generated by Django 3.2 on 2023-05-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FishImages',
        ),
    ]
