# Generated by Django 4.1.6 on 2023-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FishBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fish_name", models.CharField(blank=True, max_length=50, null=True)),
                ("scientific_name", models.CharField(max_length=100)),
                ("english_name", models.CharField(max_length=100)),
                ("prohibition_size", models.CharField(max_length=50)),
                ("habitat", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "distribution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("limit_start", models.CharField(max_length=50)),
                ("limit_end", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("image_url", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "fish_book",
                "managed": False,
            },
        ),
    ]
